#!/bin/bash

REPODIR=${PWD}

echo $REPODIR

source sources/poky/oe-init-build-env build

cat <<EOF > conf/bblayers.conf
# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "\${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \\
    ${REPODIR}/sources/poky/meta \\
    ${REPODIR}/sources/poky/meta-poky \\
    ${REPODIR}/sources/meta-openembedded/meta-oe \\
    ${REPODIR}/sources/meta-openembedded/meta-multimedia \\
    ${REPODIR}/sources/meta-openembedded/meta-networking \\
    ${REPODIR}/sources/meta-openembedded/meta-perl \\
    ${REPODIR}/sources/meta-openembedded/meta-python \\
    ${REPODIR}/sources/meta-qt5 \\
    ${REPODIR}/sources/meta-raspberrypi \\
    ${REPODIR}/sources/meta-security \\
    ${REPODIR}/sources/meta-jumpnow \\
    ${REPODIR}/sources/meta-rpi64 \\
    ${REPODIR}/sources/meta-rauc \\
    ${REPODIR}/sources/meta-rauc-community/meta-rauc-raspberrypi \\
"
EOF

cp ../sources/meta-rpi64/conf/local.conf.sample conf/local.conf
